---
apiToken:
  protocol: http
  host: localhost
  port: 8084
  path: "/otp/journeys/get"
  optimization: QUICK
  arrivalDateTime: false
  dateTime: '2020-09-30T13:00:00+02:00'
  departureCoordinates_x: 8.209198D
  departureCoordinates_y: 48.048381D
  arrivalCoordinates_x: 7.891595D
  arrivalCoordinates_y: 48.087517D
  language: de
