name: build and push to dockerhub on merge in master

on:
  push:
    branches: [ master ]
jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build and push docker image
          uses: docker/build-push-action@v1
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASS }}
            repository: blackforestsolutions/dravelopsotpmapperservice
            tags: latest