name: 'merge to master'

on:
  push:
    branches: [ master ]

jobs:
  #  docker:
  #    name: Publish - Docker Hub
  #    runs-on: ubuntu-18.04
  #    env:
  #      REPO: ${{ secrets.DOCKER_REPO }}
  #
  #    steps:
  #      - uses: actions/checkout@v1
  #      - name: Set up JDK 11
  #        uses: actions/setup-java@v1
  #        with:
  #          java-version: 1.11
  #      - name: Login to Docker Hub
  #        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
  #      - name: Build Docker image
  #        run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
  #      - name: Publish Docker image
  #        run: docker push $REPO

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: $REPO
          tag_with_ref: true