name: build and push to dockerhub on merge in master

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: setup-docker
        uses: docker-practice/actions-setup-docker@0.0.1
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build latest Docker Image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_REPO }}:latest

      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login docker.io -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Push latest Docker Image
        run: docker push ${{ secrets.DOCKER_REPO }}:latest