name: 'merge to master'

on:
  push:
    branches: [ master ]
      jobs:
        build:
          runs-on: ubuntu-latest
          env:
            REPO: ${{ secrets.DOCKER_REPO }}
          steps:
            - uses: actions/checkout@v2
            - name: docker login
              env:
                DOCKER_USER: ${{ secrets.DOCKER_USER }}
                DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS }}
              run: |
                docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            - name: docker build project
              run: |
                docker build $REPO
            - name: docker push
              run: |
                docker push $REPO